- hosts: vms
  become: yes
  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ binary_path }}"
        - "{{ script_path }}"
        - "{{ results_path }}"
      loop_control:
        label: "{{ item | basename }}"
    
    - name: Create test result subdirectories
      file:
        path: "{{ results_path }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ tests | map(attribute='name') | map('replace', '.py', '') | list }}"
      loop_control:
        label: "{{ item }}"
    
    - name: Copy binaries and set permissions
      copy:
        src: "{{ local_binary_path }}/{{ application_name }}_{{ item.0 }}{{ item.1 }}"
        dest: "{{ binary_path }}/"
        mode: '0755'
      loop: "{{ opt_levels | product(['.wasm', '_native']) }}"
      loop_control:
        label: "{{ application_name }}_{{ item.0 }}{{ item.1 }}"

    - name: Copy scripts to VM
      copy:
        src: "{{ item }}"
        dest: "{{ script_path }}/"
        mode: '0755'
      loop: "{{ local_scripts }}"
      loop_control:
        label: "{{ item | basename }}"

    - name: Run tests on VM
      shell: "python3 {{ script_path }}/{{ test.name }} {{ application_name }} {{ opt_level }}"
      loop: "{{ opt_levels | product(tests) | list }}"
      loop_control:
        loop_var: "test_item"
      vars:
        opt_level: "{{ test_item[0] }}"
        test: "{{ test_item[1] }}"
      register: test_results
      when: test.active

    - name: Fetch result files from VM
      fetch:
        src: "{{ results_path }}/{{ test_item[1].name | replace('.py', '') }}/{{ application_name }}_{{ test_item[0] }}_{{ test_item[1].name | replace('.py', '') }}.json"
        dest: "{{ local_results_path }}/vm_results/{{ test_item[1].name | replace('.py', '') }}/"
        flat: yes
      loop: "{{ opt_levels | product(tests) | list }}"
      loop_control:
        loop_var: "test_item"
      when: test_item[1].active

